
$background = rgba(1c110cff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(2b4681ff)

$inverse_surface = rgba(f4ded5ff)

$on_background = rgba(f4ded5ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(000f31ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(0d1300ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(001604ff)

$outline = rgba(ffece5ff)

$outline_variant = rgba(dbbcafff)

$primary = rgba(edefffff)

$primary_container = rgba(abc1ffff)

$primary_fixed = rgba(dae2ffff)

$primary_fixed_dim = rgba(b1c5ffff)

$scrim = rgba(000000ff)

$secondary = rgba(e9f6c1ff)

$secondary_container = rgba(bcc896ff)

$secondary_fixed = rgba(dce8b4ff)

$secondary_fixed_dim = rgba(c0cc9aff)

$shadow = rgba(000000ff)

$source_color = rgba(d24028ff)

$surface = rgba(1c110cff)

$surface_bright = rgba(5c4d46ff)

$surface_container = rgba(3b2e28ff)

$surface_container_high = rgba(463832ff)

$surface_container_highest = rgba(52443dff)

$surface_container_low = rgba(291d17ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(1c110cff)

$surface_tint = rgba(b1c5ffff)

$surface_variant = rgba(584238ff)

$tertiary = rgba(ccfdcaff)

$tertiary_container = rgba(9fce9fff)

$tertiary_fixed = rgba(beefbdff)

$tertiary_fixed_dim = rgba(a3d2a3ff)

