[general]
pgp-provider=auto
unsafe-accounts-conf=false
log-level=warn

[ui]
styleset-name=matugen
border-char-vertical="│"
border-char-horizontal="─"
dirlist-tree=true
threading-enabled=false
sort=-r date
fuzzy-complete=true
completion-delay=300ms
completion-min-chars=2
icon-encrypted=✔
icon-signed=✔
icon-unknown=✘
icon-invalid=⚠

[viewer]
pager=less -R
alternatives=text/plain,text/html
show-headers=false
header-layout=From|To,Cc|Bcc,Date,Subject
parse-http-links=true

[compose]
editor=nvim
header-layout=To|From,Subject
address-book-cmd=khard email --remove-first-line --parsable %s
reply-to-self=false
empty-subject-warning=true
no-attachment-warning=^[^>]*attach(ed|ment)

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html=html
.headers=colorize

[openers]
x-scheme-handler/http*=zen-browser {}
x-scheme-handler/https*=zen-browser {}
text/html=zen-browser {}

[hooks]
mail-received=notify-send "[$AERC_ACCOUNT/$AERC_FOLDER] New mail from $AERC_FROM_NAME" "$AERC_SUBJECT"

[templates]
new-message=new_message
quoted-reply=quoted_reply
forwards=forward_as_body
