[theme]
font_color = #ffffff
font_path = /usr/share/fonts/TTF/JetBrainsMonoNerdFont-Regular.ttf
font_size = 14.0
background_color = #1c110c
window_rounding = 10.0
frame_rounding = 6.0
background_blur = 0.95
hover_color = #edefff
active_color = e9f6c1
wallpaper_width_ratio = 0.8
