[config]
reload_apps = true
color_scheme = "dark"

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'sh ~/.local/bin/scripts/reloadway'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-color.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-color.conf'
output_path = '~/.config/hypr/colors/colors.conf'
post_hook = 'hyprctl reload'

[templates.mako]
input_path = '~/.config/matugen/templates/mako'
output_path = '~/.config/mako/mako-colors'
post_hook = 'makoctl reload'

[templates.anyrun]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/anyrun/colors.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/btop.theme'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"; gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"; gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"'

[templates.kvantum_kvconfig]
input_path = './templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.hyprwat]
input_path = '~/.config/matugen/templates/hyprwat.toml'
output_path = '~/.config/hyprwat/hyprwat.conf'
