[config]
reload_apps = true
color_scheme = "dark"


[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-color.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland-color.lua'
output_path = '~/.config/hypr/colors/colors.lua'
post_hook = 'hyprctl reload'


[templates.anyrun]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/anyrun/colors.css'

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/btop.theme'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura-colors'
output_path = '~/.config/zathura/zathurarc'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"; gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"; gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"'

[templates.kvantum_kvconfig]
input_path = '~/.config/matugen/templates/kvantum-colors.kvconfig'
output_path = '~/.config/Kvantum/matugen/matugen.kvconfig'

[templates.kvantum_svg]
input_path = '~/.config/matugen/templates/kvantum-colors.svg'
output_path = '~/.config/Kvantum/matugen/matugen.svg'

[templates.hyprwat]
input_path = '~/.config/matugen/templates/hyprwat.toml'
output_path = '~/.config/hyprwat/hyprwat.conf'

[templates.opencode]
input_path = '~/.config/matugen/templates/opencode-colors.json'
output_path = '~/.config/opencode/themes/matugen.json'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.quickshell_dynamic]
input_path = '~/.config/matugen/templates/quickshell-dynamic-island.json'
output_path = '~/.config/hypr/scripts/quickshell/qs_colors.json'
post_hook = 'touch /tmp/qs_colors_updated'

[templates.aerc]
input_path = '~/.config/matugen/templates/aerc'
output_path = '~/.config/aerc/stylesets/matugen'

# [templates.mako]
# input_path = '~/.config/matugen/templates/mako'
# output_path = '~/.config/mako/mako-colors'
# post_hook = 'makoctl reload'

# [templates.waybar]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/waybar/colors.css'
# post_hook = 'sh ~/.local/bin/scripts/reloadway'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qt5ct.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'
post_hook = 'sed -i "s/^theme=.*/theme=matugen/" ~/.config/Kvantum/kvantum.kvconfig'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qt6ct.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'
