# ############################################################################################################
# ##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
# ##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
# ## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
# ## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
# ## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
# ## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
# ## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
# ##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
# ##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
# ##                                                                                                        ##
# ## Vicious Viper Config                                                                                   ##
# ## Created by Cybersnake                                                                                  ##
# ############################################################################################################

# ## Sourcing Modules

source = modules/default-apps.conf
source = modules/web-apps.conf
source = modules/env-var.conf
source = modules/startup.conf
source = modules/monitors.conf
source = modules/xwayland.conf
source = modules/ecosystem.conf
source = modules/input.conf
source = colors/colors.conf
source = modules/general.conf
source = modules/deco.conf
source = modules/animations.conf
source = modules/layout.conf
source = modules/misc.conf
source = modules/keybinds.conf
source = modules/window-rules.conf
source = modules/layer-rules.conf
source = modules/workspace-rules.conf
