general {
    lock_cmd = ~/.config/hypr/scripts/lock.sh
    before_sleep_cmd = ~/.config/hypr/scripts/lock.sh
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 0
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = ~/.config/hypr/scripts/lock.sh
}

listener {
    timeout = 900
    on-timeout = hyprctl dispatch dpms off
}
