# ########################
# ## DECORATION         ##
# ########################

decoration {
    rounding          = 10
    rounding_power    = 5
    inactive_opacity  = 0.90
    active_opacity    = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled       = false
        range         = 20
        scale         = 1.0
        color         = $shadow
        color_inactive = $shadow
    }

    blur {
        enabled    = true
        size       = 8
        passes     = 2
        brightness = 0.8
        contrast   = 1.5
        noise      = 0
        xray       = false
        popups     = false
        ignore_opacity = true
        new_optimizations = true
    }
}
