# ########################
# ## DECORATION         ##
# ########################

decoration {
    rounding          = 0
    rounding_power    = 0
    inactive_opacity  = 0.90
    active_opacity    = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled       = false
        range         = 20
        scale         = 1.0
        color         = $shadow
        color_inactive = $shadow
    }

    blur {
        enabled    = true
        size       = 3
        passes     = 2
        brightness = 0.6
        contrast   = 1.0
        noise      = 0
        xray       = false
        popups     = false
    }
}
