# ##########################
# ## Default Applications ##
# ##########################

$launcher     = rofi -show drun
$browser      = zen-browser
$incogbrowser = zen-browser -private-window
$sysmon       = btop
$music        = cmus
$editor       = nvim
$term         = kitty
