# ########################
# ## LAYER RULES        ##
# ########################

layerrule {
    name      = notify-slide
    animation = slide
    # blur = 1
    match:namespace = notifications
}

layerrule {
    name      = rofi-slide
    animation = slide
    dim_around = 0
    match:namespace = rofi
}

layerrule {
    name      = waybar-slide
    animation = slide
    blur      = 1
    match:namespace = waybar
}

layerrule {
    name      = hyprlock-slide
    animation = slide
    match:namespace = hyprlock
}

layerrule {
    name      = pavucontrol-slide
    animation = slide
    match:class = org.pulseaudio.pavucontrol
}
