# ########################
# ## LAYOUT             ##
# ########################

dwindle {
    pseudotile         = yes
    preserve_split     = yes
    force_split        = 1
    default_split_ratio = 1
}

master {
    new_status = dwindle
}
