# ######################
# ## Startup Services ##
# ######################

exec-once = sleep 1 && xdg-portal-hyprland

# Bluetooth
exec-once = rfkill block bluetooth

# Auth agent
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Import env for Qt/systemd services
exec-once = systemctl --user import-environment XDG_SESSION_TYPE XDG_CURRENT_DESKTOP WAYLAND_DISPLAY QT_QPA_PLATFORMTHEME

# Wallpaper daemon, restore last wallpaper,bar + notifications
exec-once = awww-daemon --format xrgb
exec-once = sleep 0.3 && restore-wall
exec-once = waybar
exec-once = mako
# exec-once = qs -p ~/.config/quickshell/dynamic/modules/Main.qml
# exec-once = qs -p ~/.config/quickshell/dynamic/modules/TopBar.qml
# exec-once = qs -p ~/.config/hypr/scripts/quickshell/DynamicIsland.qml
# exec-once = qs -p ~/.config/quickshell/dynamic/modules/DynamicIsland.qml
# exec-once = qs -p ~/.config/hypr/scripts/quickshell/AppLauncher.qml
# exec-once = qs -p ~/.config/quickshell/dynamic/modules/AppLauncher.qml
# exec-once = qs -p ~/.config/hypr/scripts/quickshell/ClipboardViewer.qml
# exec-once = qs -p ~/.config/quickshell/dynamic/modules/ClipboardViewer.qml
# exec-once = python3 ~/.config/hypr/scripts/quickshell/focustime/focus_daemon.py &
# exec-once = ~/.config/quickshell/dynamic/init.sh


# Clipboard
exec-once = wl-clip-persist -c both
exec-once = wl-paste --type text --watch cliphist store

# Keyring + idle daemon
exec-once = /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh
exec-once = hypridle
