
$background = rgba(1a1111ff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(743432ff)

$inverse_surface = rgba(f1deddff)

$on_background = rgba(f1deddff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(2c0103ff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(200b0aff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(1a0f00ff)

$outline = rgba(ffeceaff)

$outline_variant = rgba(d4bebcff)

$primary = rgba(ffeceaff)

$primary_container = rgba(ffaea8ff)

$primary_fixed = rgba(ffdad7ff)

$primary_fixed_dim = rgba(ffb3aeff)

$scrim = rgba(000000ff)

$secondary = rgba(ffeceaff)

$secondary_container = rgba(e3b9b6ff)

$secondary_fixed = rgba(ffdad7ff)

$secondary_fixed_dim = rgba(e7bdb9ff)

$shadow = rgba(000000ff)

$source_color = rgba(e54b4bff)

$surface = rgba(1a1111ff)

$surface_bright = rgba(594d4cff)

$surface_container = rgba(382e2dff)

$surface_container_high = rgba(443938ff)

$surface_container_highest = rgba(504443ff)

$surface_container_low = rgba(271d1dff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(1a1111ff)

$surface_tint = rgba(ffb3aeff)

$surface_variant = rgba(534342ff)

$tertiary = rgba(ffeed5ff)

$tertiary_container = rgba(debe89ff)

$tertiary_fixed = rgba(ffdea7ff)

$tertiary_fixed_dim = rgba(e2c28cff)

