
$background = rgba(111318ff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(284878ff)

$inverse_surface = rgba(e2e2e9ff)

$on_background = rgba(e2e2e9ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(00112bff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(081121ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(1d0823ff)

$outline = rgba(eeeff9ff)

$outline_variant = rgba(c0c2ccff)

$primary = rgba(ebf0ffff)

$primary_container = rgba(a5c3fcff)

$primary_fixed = rgba(d6e3ffff)

$primary_fixed_dim = rgba(aac7ffff)

$scrim = rgba(000000ff)

$secondary = rgba(ebf0ffff)

$secondary_container = rgba(bac3d8ff)

$secondary_fixed = rgba(dae2f9ff)

$secondary_fixed_dim = rgba(bec7dcff)

$shadow = rgba(000000ff)

$source_color = rgba(090e17ff)

$surface = rgba(111318ff)

$surface_bright = rgba(4e5056ff)

$surface_container = rgba(2e3036ff)

$surface_container_high = rgba(393b41ff)

$surface_container_highest = rgba(45474cff)

$surface_container_low = rgba(1d2024ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(111318ff)

$surface_tint = rgba(aac7ffff)

$surface_variant = rgba(44474eff)

$tertiary = rgba(ffe9ffff)

$tertiary_container = rgba(d8b8dcff)

$tertiary_fixed = rgba(f9d8fdff)

$tertiary_fixed_dim = rgba(dcbce0ff)

