
$background = rgba(1c110dff)

$error = rgba(ffece9ff)

$error_container = rgba(ffaea4ff)

$inverse_on_surface = rgba(000000ff)

$inverse_primary = rgba(1e487fff)

$inverse_surface = rgba(f5ded7ff)

$on_background = rgba(f5ded7ff)

$on_error = rgba(000000ff)

$on_error_container = rgba(000000ff)

$on_primary = rgba(000000ff)

$on_primary_container = rgba(000000ff)

$on_primary_fixed = rgba(000000ff)

$on_primary_fixed_variant = rgba(00112aff)

$on_secondary = rgba(000000ff)

$on_secondary_container = rgba(000000ff)

$on_secondary_fixed = rgba(000000ff)

$on_secondary_fixed_variant = rgba(101300ff)

$on_surface = rgba(ffffffff)

$on_surface_variant = rgba(ffffffff)

$on_tertiary = rgba(000000ff)

$on_tertiary_container = rgba(000000ff)

$on_tertiary_fixed = rgba(000000ff)

$on_tertiary_fixed_variant = rgba(011600ff)

$outline = rgba(ffece7ff)

$outline_variant = rgba(dbbcb2ff)

$primary = rgba(ebf0ffff)

$primary_container = rgba(a2c4ffff)

$primary_fixed = rgba(d6e3ffff)

$primary_fixed_dim = rgba(a8c8ffff)

$scrim = rgba(000000ff)

$secondary = rgba(f0f4bcff)

$secondary_container = rgba(c2c792ff)

$secondary_fixed = rgba(e2e7afff)

$secondary_fixed_dim = rgba(c6cb95ff)

$shadow = rgba(000000ff)

$source_color = rgba(e54b4bff)

$surface = rgba(1c110dff)

$surface_bright = rgba(5c4d48ff)

$surface_container = rgba(3b2d29ff)

$surface_container_high = rgba(473834ff)

$surface_container_highest = rgba(53433fff)

$surface_container_low = rgba(291d19ff)

$surface_container_lowest = rgba(000000ff)

$surface_dim = rgba(1c110dff)

$surface_tint = rgba(a8c8ffff)

$surface_variant = rgba(58423aff)

$tertiary = rgba(d3fbc2ff)

$tertiary_container = rgba(a6cd97ff)

$tertiary_fixed = rgba(c6eeb5ff)

$tertiary_fixed_dim = rgba(aad19bff)

