# ########################
# ## DECORATION         ##
# ########################

decoration {
    rounding          = 10
    rounding_power    = 5
    inactive_opacity  = 0.90
    active_opacity    = 1.0
    fullscreen_opacity = 1.0

    shadow {
        enabled       = false
        range         = 50
        scale         = 1.0
        color         = $shadow
        color_inactive = $shadow
    }

    blur {
        enabled    = true
        size       = 10
        passes     = 3
        brightness = 0.8
        contrast   = 1.0
        vibrancy   = 0.50
        vibrancy_darkness = 0.3
        noise      = 0
        xray       = false
        popups     = true
        ignore_opacity = false
        new_optimizations = true
    }
}
