# ########################
# ## WINDOW RULES       ##
# ########################

windowrule {
    name  = media-viewer-float
    float = 1
    match:title = ^(Media viewer)$
}

windowrule {
    name  = wiremix-float
    float = 1
    size  = 1000 800
    match:class = ^(kitty)$
    match:title = ^(wiremix)$
}

windowrule {
    name  = pavucontrol-float
    float = 1
    size  = 1000 800
    match:class = ^(org.pulseaudio.pavucontrol)$
    match:title = ^(Volume Control)$
}


windowrule {
    name  = airpods-float
    float = 1
    size  = 1000 800
    match:class = ^(kitty)$
    match:title = ^(airpods-tui)$
}

windowrule {
    name  = pip-float
    float           = 1
    pin             = 1
    keep_aspect_ratio = 1
    match:title = ^(Picture-in-Picture)$
}

windowrule {
    name  = open-files-size
    float = 1
    size  = 1000 800
    match:title = ^(Open Files)$
}

windowrule {
    name  = save-file-size
    size  = 1000 800
    match:title = ^(Save File)$
}

windowrule {
    name  = localsend-open-float
    float = 1
    size  = 1000 800
    match:class = ^(localsend)$
}

windowrule {
    name  = zen-twilight-open-float
    float = 1
    match:class = ^(zen-browser)$
    match:title = ^(Open Files)$
}


windowrule {
    name  = zen-upload-float
    float = 1
    match:class = ^(xdg-desktop-portal-gtk)$
    match:title = ^(File Upload)$
}


windowrule {
    name  = zen-twilight-save-float
    float = 1
    match:class = ^(zen-browser)$
    match:title = ^(Save File)$
}

windowrule {
    name  = zen-twilight-download-float
    float = 1
    size  = 1000 700
    match:class = ^(zen-browser)$
    match:title = ^(Library)$
}

