#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Bluetooth Script                                                                                       ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

if [[ $(pidof bluetoothctl) ]]; then
	pkill bluetoothctl
fi

rfkill unblock bluetooth
bluetoothctl power on
devices=$(bluetoothctl devices | awk '{print $3}')
selected_device=$(echo "$devices" | rofi -dmenu -p "Select Bluetooth Device:")

if [ -n "$selected_device" ]; then
	# Connect to the selected device
	bluetoothctl connect "$selected_device"
	echo "Connecting to $selected_device..."
	sleep 5 # You can adjust the sleep duration as needed
	echo "Connection attempt finished"
else
	bluetoothctl power off
	rfkill block bluetooth
fi

killall bluetoothctl
killall awk
