#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Bluetooth Script                                                                                       ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

rfkill unblock bluetooth
device_amount=$(bluetoothctl devices | wc -l)

if [[ $device_amount = 1 ]]; then
	MAC=$(bluetoothctl devices | awk {'print $2'})
		[ -z $MAC ] && MAC=NoDeviceFound # Prevents accidental disconnect error
else
	select=$(bluetoothctl devices | awk {'print $3'} | rofi -dmenu -l 10)
	MAC=$(bluetoothctl devices | grep $select | awk {'print $2'}) 
		[ -z $MAC ] && MAC=NoDeviceFound # Prevents accidental disconnect error
fi

connect=$(bluetoothctl info $MAC | grep Connected: | awk '{print $2}')
if [[ $connect = no ]]; then 
	notify-send "Attempting to Connect"
	bluetoothctl connect $MAC || notify-send "Failed to Connect"
elif [[ $connect = yes ]]; then
	notify-send "Attempting to Disconnect"
	bluetoothctl disconnect $MAC 
fi
