#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Config Edit Script                                                                                     ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

options=("aliases
cava
dunst
foot
hyprland
lf
mpv
mpv-input
nvim
rofi
swaylock
waybar
waybar-Style
yay
yt-dlp
zsh")

choice=$(echo -e "${options[@]}" | rofi -dmenu -I -p 'Edit config file: ')

case "$choice" in
aliases)
	choice="$HOME/.config/zsh/.zsh_aliases"
	;;
cava)
	choice="$HOME/.config/cava/config"
	;;
dunst)
	choice="$HOME/.config/dunst/dunstrc"
	;;
foot)
    choice="$HOME/.config/foot/foot.ini"
    ;;
hyprland)
	choice="$HOME/.config/hypr/hyprland.conf"
	;;
lf)
	choice="$HOME/.config/lf/lfrc"
	;;
mpv)
	choice="$HOME/.config/mpv/mpv.conf"
	;;
mpv-input)
	choice="$HOME/.config/mpv/input.conf"
	;;
nvim)
    choice="$HOME/.config/nvim"
    ;;
rofi)
	choice="$HOME/.config/rofi/config.rasi"
	;;
swaylock)
	choice="$HOME/.config/swaylock/config"
	;;
waybar)
	choice="$HOME/.config/waybar/config.jsonc"
	;;
waybar-Style)
	choice="$HOME/.config/waybar/style.css"
	;;
yay)
	choice="$HOME/.config/yay/config.json"
	;;
yt-dlp)
	choice="$HOME/.config/yt-dlp/config"
	;;
zsh)
	choice="$HOME/.config/zsh/.zshrc"
	;;
*)
	exit 1
	;;
esac

foot -e lvim "$choice"
