#!/usr/bin/env bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
##                                                                                                        ##
## Config Editor created by Cybersnake                                                                    ##
############################################################################################################

options=("alacritty
aliases
cava
deadbeef
dunst
hyprland
lf
mpv
mpv-input
rofi
rofi-wifi
swaylock
topgrade
waybar
waybar-Style
yay
yt-dlp
zsh
quit")

choice=$(echo -e "${options[@]}" | rofi -dmenu -p 'Edit config file: ')

case "$choice" in
quit)
	notify-send "Program terminated." && exit 1
	;;
alacritty)
	choice="$HOME/.config/alacritty/alacritty.yml"
	;;
aliases)
	choice="$HOME/.config/zsh/.zsh_aliases"
	;;
cava)
	choice="$HOME/.config/cava/config"
	;;
deadbeef)
	choice="$HOME/.config/deadbeef/config"
	;;
dunst)
	choice="$HOME/.config/dunst/dunstrc"
	;;
hyprland)
	choice="$HOME/.config/hypr/hyprland.conf"
	;;
lf)
	choice="$HOME/.config/lf/lfrc"
	;;
mpv)
	choice="$HOME/.config/mpv/mpv.conf"
	;;
mpv-input)
	choice="$HOME/.config/mpv/input.conf"
	;;
rofi)
	choice="$HOME/.config/rofi/config.rasi"
	;;
rofi-wifi)
	choice="$HOME/.config/rofi/wifi"
	;;
swaylock)
	choice="$HOME/.config/swaylock/config"
	;;
topgrade)
	choice="$HOME/.config/topgrade.toml"
	;;
waybar)
	choice="$HOME/.config/waybar/config.jsonc"
	;;
waybar-Style)
	choice="$HOME/.config/waybar/style.css"
	;;
yay)
	choice="$HOME/.config/yay/config.json"
	;;
yt-dlp)
	choice="$HOME/.config/yt-dlp/config"
	;;
zsh)
	choice="$HOME/.config/zsh/.zshrc"
	;;
*)
	exit 1
	;;
esac
alacritty -e nvim "$choice"
