#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

# Function to display usage instructions
usage() {
	echo "Usage: $0 -f <compressed_file> -d <output_directory>"
	exit 1
}

# Check if the required number of arguments is provided
if [ "$#" -ne 4 ]; then
	usage
fi

# Parse command-line arguments
while getopts ":f:d:" opt; do
	case $opt in
	f)
		compressed_file="$OPTARG"
		;;
	d)
		output_directory="$OPTARG"
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		usage
		;;
	:)
		echo "Option -$OPTARG requires an argument." >&2
		usage
		;;
	esac
done

# Check if the compressed file exists
if [ ! -f "$compressed_file" ]; then
	echo "Error: The specified compressed file does not exist."
	usage
fi

# Check if the output directory exists or create it
if [ ! -d "$output_directory" ]; then
	mkdir -p "$output_directory"
fi

# Determine the file format and extract accordingly
case "$compressed_file" in
*.zip)
	unzip -q "$compressed_file" -d "$output_directory" | pv
	;;
*.rar)
	unrar x -o+ -inul "$compressed_file" "$output_directory" | pv
	;;
*.tar)
	tar -xvf "$compressed_file" -C "$output_directory" | pv
	;;
*.tar.gz | *.tgz)
	tar -xzvf "$compressed_file" -C "$output_directory" | pv
	;;
*.tar.bz2 | *.tbz2)
	tar -xjvf "$compressed_file" -C "$output_directory" | pv
	;;
*.tar.xz | *.txz)
	tar -xJvf "$compressed_file" -C "$output_directory" | pv
	;;
*.7z)
	7z x "$compressed_file" -o"$output_directory" | pv
	;;
*)
	echo "Unsupported file format: $compressed_file"
	usage
	;;
esac

notify-send "Extraction completed to $output_directory"
