#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Power Menu                                                                                       ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

DIR="$HOME/.config"
rofi_cmd="rofi -theme $DIR/rofi/themes/powermenu.rasi"
uptime=$(uptime -p | sed -e 's/up //g')

# Options
Shutdown=""
Reboot=""
Lock=""
Suspend=""
Logout=""

options="$Shutdown\n$Reboot\n$Lock\n$Suspend\n$Logout"


# Show menu
#selection="$(echo -e "Shut Down\nRestart\nSuspend\nLog Out" | rofi -l 4 -dmenu -steal-focus -p "$up_time")"
chosen="$(echo -e "$options" | $rofi_cmd -p "UPTIME - $uptime" -dmenu -selected-row 2)"

# Command for specific choices
case $chosen in
"$Shutdown")
	systemctl poweroff
;;
"$Reboot")
	systemctl reboot
;;
"$Suspend")
	systemctl suspend
;;
"$Lock")
  lock
;;
"$Logout")
  killall Hyprland
;;
esac
