#!/bin/bash
###############################
#  CYBERSNAKE SCRIPT EDITING  #
###############################

list_files() {
	find "$1" -type f
}

directory="/home/cybersnake/.local/bin/scripts"
files=$(list_files "$directory")

selected_file=$(echo "$files" | rofi -dmenu -i -p "Edit Scripts:")

if [ -n "$selected_file" ]; then
	alacritty -e nvim "$selected_file"
else
	notify-send "No file selected."
fi
