#!/bin/bash

############################################################################################################
##   ______  __      __  _______   ________  _______    ______   __    __   ______   __    __  ________   ##
##  /      \|  \    /  \|       \ |        \|       \  /      \ |  \  |  \ /      \ |  \  /  \|        \  ##
## |  $$$$$$\\$$\  /  $$| $$$$$$$\| $$$$$$$$| $$$$$$$\|  $$$$$$\| $$\ | $$|  $$$$$$\| $$ /  $$| $$$$$$$$  ##
## | $$   \$$ \$$\/  $$ | $$__/ $$| $$__    | $$__| $$| $$___\$$| $$$\| $$| $$__| $$| $$/  $$ | $$__      ##
## | $$        \$$  $$  | $$    $$| $$  \   | $$    $$ \$$    \ | $$$$\ $$| $$    $$| $$  $$  | $$  \     ##
## | $$   __    \$$$$   | $$$$$$$\| $$$$$   | $$$$$$$\ _\$$$$$$\| $$\$$ $$| $$$$$$$$| $$$$$\  | $$$$$     ##
## | $$__/  \   | $$    | $$__/ $$| $$_____ | $$  | $$|  \__| $$| $$ \$$$$| $$  | $$| $$ \$$\ | $$_____   ##
##  \$$    $$   | $$    | $$    $$| $$     \| $$  | $$ \$$    $$| $$  \$$$| $$  | $$| $$  \$$\| $$     \  ##
##   \$$$$$$     \$$     \$$$$$$$  \$$$$$$$$ \$$   \$$  \$$$$$$  \$$   \$$ \$$   \$$ \$$   \$$ \$$$$$$$$  ##
##                                                                                                        ##
## Created by Cybersnake                                                                                  ##
############################################################################################################

if [[ $(pidof aria2c) ]]; then
	pkill aria2c
	notify-send "Aria Server Killed"
fi

if [[ $(pidof wl-copy) ]]; then
	pkill wl-copy
	notify-send "Clipboard Cleaned"
fi

if [[ $(pidof gvfsd) ]]; then
	pkill gvfsd
fi

if [[ $(pidof tumblerd) ]]; then
	pkill tumblerd
	notify-send "Thumbnail Cache Cleaned"
fi

if [[ $(pidof gvfs-udisks2-volume-monitor) ]]; then
	pkill gvfs-udisks2-vo
fi

if [[ $(pidof xfconfd) ]]; then
	pkill xfconfd
fi

if [[ $(pidof lf) ]]; then
	pkill lf
	notify-send "Lf Killed"
fi

if [[ $(pidof persepolis) ]]; then
	pkill persepolis
	notify-send "Persepolis Killed"
fi
