# ##########################
# ## Default Applications ##
# ##########################

$term         = kitty
$editor       = nvim
$browser      = zen-browser
$incogbrowser = zen-browser --private-window
$launcher     = rofi -show drun
$sysmon       = kitty -e btop
$music        = kitty -e cmus
