# ########################
# ## GENERAL            ##
# ########################

general {
    gaps_in               = 2
    gaps_out              = 0
    layout                = dwindle #scrolling
    border_size           = 2
    col.active_border     = $tertiary
    col.inactive_border   = $shadow
    resize_on_border      = true
    allow_tearing         = false
    extend_border_grab_area = 0
}
