# ################
# ## INPUT      ##
# ################

input {
    kb_layout          = us
    numlock_by_default = true
    follow_mouse       = 1
    sensitivity        = 0.3
    repeat_rate        = 60
    repeat_delay       = 400
    scroll_method      = 2fg

    touchpad {
        natural_scroll        = no
        disable_while_typing  = yes
        middle_button_emulation = no
        drag_lock             = no
        tap-to-click          = true
        scroll_factor         = 0.8
    }
}

cursor {
    sync_gsettings_theme = false
    enable_hyprcursor    = true
    no_hardware_cursors  = false
}
