# ########################
# ## LAYER RULES        ##
# ########################

layerrule {
    name      = notify-slide
    animation = slide
    blur = 1
    ignore_alpha = 0.2
    match:namespace = notifications
}

layerrule {
    name      = hyprwat-slide
    animation = slide
    # blur = 1
    match:namespace = popup_menu
}

layerrule {
    name      = rofi-slide
    animation = slide
    dim_around = 1
    # blur       = 1
    match:namespace = rofi
}

layerrule {
    name      = waybar-slide
    animation = slide
    blur      = 1
    xray      = 0
    ignore_alpha = 0.2
    match:namespace = waybar
}

layerrule {
    name      = hyprlock-slide
    animation = slide
    match:namespace = hyprlock
}

layerrule {
    name      = pavucontrol-slide
    animation = slide
    match:class = org.pulseaudio.pavucontrol
}
